### PR TITLE
Feature/frendships v1

### PR DESCRIPTION
**Pull request by Dipeshtwis**
I made this project alone because my partner took a leave for a month and the success team suggested to do alone.

what does this PR do : 

- User can send a request to another user
- Another user can accept or reject the friend request
- It shows if any request is in the pending state
- Add unit and integration testing

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thank you for the job done so far.
However, there are some missing requirements

1. It's indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png), that the posts timeline must include posts written by logged-in user and their friends. It's not what is implemented in your application.

2. There should a button to invite user to friendship on users list page and on single user page.[Read it here[(https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png). In your appication, it's only available in the **User list** page. Kindly add it on the single user page

3. As you can see in the following screenshot
Screenshot_2020-09-04_13-45-22
The invitation of Bob is accepted by Alice (The flash message) but there is still a **Invite** button instead of **Unfriend**. 
Kindly fix that.

4. Kindly remove logics from your views Implement them into views helpers

5. For the unit tests, kindly use **shoulda-matcher** gem. 
Also, add **integration tests** for friendship feature.

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

**Comment by Dipeshtwis** [comment]
The update project includes

- post timeline includes only the logged-in users and his friend post.
- Use shoulda matcher gem for unit and integration testing
- Add the button invite on single user profile page also.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
- [x] When the friendship request is accepted, it only works on one side while on the other it's still pending. 
- [x] Let's implement linter checks for this project.
- [x] Let's write a proper integration test using capybara and Rspec
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by Dipeshtwis** [comment]
The update project includes : 

- when invitation accepted, now no invite button will show for that friend.
- Added feature test using capybara
- Enable the Github action

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello @Dipeshtwis  ,  you have done a brilliant job with this project. :clap:

#### You can merge !!!

**Pull request merged**
